/*
Generated by Yara-Rules
On 07-10-2018
*/
include "/tmp/yara/Webshells/WShell_APT_Laudanum.yar"
include "/tmp/yara/Webshells/WShell_PHP_Anuna.yar"
include "/tmp/yara/Webshells/WShell_PHP_in_images.yar"
include "/tmp/yara/Webshells/WShell_THOR_Webshells.yar"
include "/tmp/yara/Webshells/Wshell_ChineseSpam.yar"
include "/tmp/yara/Webshells/Wshell_fire2013.yar"
